// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/entities/database_metadata_entity.dart';
import 'core/database/entities/invoice_entity.dart';
import 'core/database/entities/invoice_item_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8921434432553373422),
    name: 'DatabaseMetadataEntity',
    lastPropertyId: const obx_int.IdUid(4, 3643071994016781563),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6931778386883607773),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1572597354653537197),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8225976486212192645),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5318725767002560801),
        name: 'value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3643071994016781563),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2710519800567843983),
    name: 'InvoiceEntity',
    lastPropertyId: const obx_int.IdUid(30, 6884250741628774964),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3079184095061451688),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5980377059448444664),
        name: 'merchant',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 171865172451866644),
        name: 'merchantNormalized',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 9154832734347378190),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4944936005697346823),
        name: 'documentType',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 8953472198375689066),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2775593172922476841),
        name: 'purchaseDate',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(7, 5311294656040773956),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3100164715877639181),
        name: 'totalMinor',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(8, 8368154445385511266),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3670264727628614195),
        name: 'currencyCode',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 3885248533064431393),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6125850420181387561),
        name: 'warrantyMonths',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6638178550246040538),
        name: 'warrantyEndDate',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(10, 6006889428533657188),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1514928858998725598),
        name: 'invoiceNumber',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 1010180079252887381),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4295785881058077758),
        name: 'rawExtractedText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7798973669944971901),
        name: 'searchableText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 429315488774195355),
        name: 'keywordText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4408019907279837061),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8691153843913632104),
        name: 'thumbnailPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8064367121695413798),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3475944700035130751),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 5674699518843013707),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7143753898001492162),
        name: 'embeddingModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 374733033470212667),
        name: 'embeddingDimensions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1725022977967834170),
        name: 'searchTextSchemaVersion',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(13, 8163934728334606683),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1288771452257188839),
        name: 'extractionModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 3179250191803199211),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 137729607138466433),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 8327496945878684493),
        name: 'reviewedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 5372395655841535369),
        name: 'embeddingStatus',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(11, 8585492971084280388),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 1753796824999705605),
        name: 'embeddingSchemaVersion',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(12, 7879334667745668386),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 204062106447988342),
        name: 'embeddingUpdatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 2459370597045458659),
        name: 'embeddingFailureCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 8633708862621090467),
        name: 'documentTypeNormalized',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 3409279870630035987),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 6884250741628774964),
        name: 'embeddingAttemptId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7266021108998744756),
    name: 'InvoiceItemEntity',
    lastPropertyId: const obx_int.IdUid(7, 7525869773311577887),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 549211893111121153),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7620150830275011697),
        name: 'invoiceId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 5092787116082410787),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5824603851181885386),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8251323373360254933),
        name: 'nameNormalized',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 881694135585227179),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7002408373483038361),
        name: 'unitPriceMinor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7525869773311577887),
        name: 'lineTotalMinor',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7266021108998744756),
    lastIndexId: const obx_int.IdUid(14, 3409279870630035987),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DatabaseMetadataEntity: obx_int.EntityDefinition<DatabaseMetadataEntity>(
      model: _entities[0],
      toOneRelations: (DatabaseMetadataEntity object) => [],
      toManyRelations: (DatabaseMetadataEntity object) => {},
      getId: (DatabaseMetadataEntity object) => object.id,
      setId: (DatabaseMetadataEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DatabaseMetadataEntity object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = DatabaseMetadataEntity(
          id: idParam,
          key: keyParam,
          value: valueParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    InvoiceEntity: obx_int.EntityDefinition<InvoiceEntity>(
      model: _entities[1],
      toOneRelations: (InvoiceEntity object) => [],
      toManyRelations: (InvoiceEntity object) => {},
      getId: (InvoiceEntity object) => object.id,
      setId: (InvoiceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (InvoiceEntity object, fb.Builder fbb) {
        final merchantOffset = object.merchant == null
            ? null
            : fbb.writeString(object.merchant!);
        final merchantNormalizedOffset = object.merchantNormalized == null
            ? null
            : fbb.writeString(object.merchantNormalized!);
        final documentTypeOffset = object.documentType == null
            ? null
            : fbb.writeString(object.documentType!);
        final currencyCodeOffset = object.currencyCode == null
            ? null
            : fbb.writeString(object.currencyCode!);
        final invoiceNumberOffset = object.invoiceNumber == null
            ? null
            : fbb.writeString(object.invoiceNumber!);
        final rawExtractedTextOffset = object.rawExtractedText == null
            ? null
            : fbb.writeString(object.rawExtractedText!);
        final searchableTextOffset = fbb.writeString(object.searchableText);
        final keywordTextOffset = fbb.writeString(object.keywordText);
        final imagePathOffset = fbb.writeString(object.imagePath);
        final thumbnailPathOffset = object.thumbnailPath == null
            ? null
            : fbb.writeString(object.thumbnailPath!);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final embeddingModelIdOffset = object.embeddingModelId == null
            ? null
            : fbb.writeString(object.embeddingModelId!);
        final extractionModelIdOffset = object.extractionModelId == null
            ? null
            : fbb.writeString(object.extractionModelId!);
        final embeddingStatusOffset = fbb.writeString(object.embeddingStatus);
        final embeddingFailureCodeOffset = object.embeddingFailureCode == null
            ? null
            : fbb.writeString(object.embeddingFailureCode!);
        final documentTypeNormalizedOffset =
            object.documentTypeNormalized == null
            ? null
            : fbb.writeString(object.documentTypeNormalized!);
        final embeddingAttemptIdOffset = object.embeddingAttemptId == null
            ? null
            : fbb.writeString(object.embeddingAttemptId!);
        fbb.startTable(31);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, merchantOffset);
        fbb.addOffset(2, merchantNormalizedOffset);
        fbb.addOffset(3, documentTypeOffset);
        fbb.addInt64(4, object.purchaseDate?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.totalMinor);
        fbb.addOffset(6, currencyCodeOffset);
        fbb.addInt64(7, object.warrantyMonths);
        fbb.addInt64(8, object.warrantyEndDate?.millisecondsSinceEpoch);
        fbb.addOffset(9, invoiceNumberOffset);
        fbb.addOffset(10, rawExtractedTextOffset);
        fbb.addOffset(11, searchableTextOffset);
        fbb.addOffset(12, keywordTextOffset);
        fbb.addOffset(13, imagePathOffset);
        fbb.addOffset(14, thumbnailPathOffset);
        fbb.addOffset(15, sourceTypeOffset);
        fbb.addOffset(16, embeddingOffset);
        fbb.addOffset(17, embeddingModelIdOffset);
        fbb.addInt64(18, object.embeddingDimensions);
        fbb.addInt64(19, object.searchTextSchemaVersion);
        fbb.addOffset(20, extractionModelIdOffset);
        fbb.addInt64(21, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(22, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(23, object.reviewedAt.millisecondsSinceEpoch);
        fbb.addOffset(24, embeddingStatusOffset);
        fbb.addInt64(25, object.embeddingSchemaVersion);
        fbb.addInt64(26, object.embeddingUpdatedAt?.millisecondsSinceEpoch);
        fbb.addOffset(27, embeddingFailureCodeOffset);
        fbb.addOffset(28, documentTypeNormalizedOffset);
        fbb.addOffset(29, embeddingAttemptIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final purchaseDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final warrantyEndDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final embeddingUpdatedAtValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 56);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final merchantParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final merchantNormalizedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final documentTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final documentTypeNormalizedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final purchaseDateParam = purchaseDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(purchaseDateValue);
        final totalMinorParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final currencyCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final warrantyMonthsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final warrantyEndDateParam = warrantyEndDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(warrantyEndDateValue);
        final invoiceNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final rawExtractedTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final searchableTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final keywordTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final thumbnailPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final embeddingModelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final embeddingDimensionsParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 40);
        final embeddingStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final embeddingSchemaVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          54,
          0,
        );
        final embeddingUpdatedAtParam = embeddingUpdatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(embeddingUpdatedAtValue);
        final embeddingFailureCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final embeddingAttemptIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final searchTextSchemaVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final extractionModelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 46, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 48, 0),
        );
        final reviewedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 50, 0),
        );
        final object = InvoiceEntity(
          id: idParam,
          merchant: merchantParam,
          merchantNormalized: merchantNormalizedParam,
          documentType: documentTypeParam,
          documentTypeNormalized: documentTypeNormalizedParam,
          purchaseDate: purchaseDateParam,
          totalMinor: totalMinorParam,
          currencyCode: currencyCodeParam,
          warrantyMonths: warrantyMonthsParam,
          warrantyEndDate: warrantyEndDateParam,
          invoiceNumber: invoiceNumberParam,
          rawExtractedText: rawExtractedTextParam,
          searchableText: searchableTextParam,
          keywordText: keywordTextParam,
          imagePath: imagePathParam,
          thumbnailPath: thumbnailPathParam,
          sourceType: sourceTypeParam,
          embedding: embeddingParam,
          embeddingModelId: embeddingModelIdParam,
          embeddingDimensions: embeddingDimensionsParam,
          embeddingStatus: embeddingStatusParam,
          embeddingSchemaVersion: embeddingSchemaVersionParam,
          embeddingUpdatedAt: embeddingUpdatedAtParam,
          embeddingFailureCode: embeddingFailureCodeParam,
          embeddingAttemptId: embeddingAttemptIdParam,
          searchTextSchemaVersion: searchTextSchemaVersionParam,
          extractionModelId: extractionModelIdParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          reviewedAt: reviewedAtParam,
        );

        return object;
      },
    ),
    InvoiceItemEntity: obx_int.EntityDefinition<InvoiceItemEntity>(
      model: _entities[2],
      toOneRelations: (InvoiceItemEntity object) => [],
      toManyRelations: (InvoiceItemEntity object) => {},
      getId: (InvoiceItemEntity object) => object.id,
      setId: (InvoiceItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (InvoiceItemEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final nameNormalizedOffset = fbb.writeString(object.nameNormalized);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.invoiceId);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, nameNormalizedOffset);
        fbb.addFloat64(4, object.quantity);
        fbb.addInt64(5, object.unitPriceMinor);
        fbb.addInt64(6, object.lineTotalMinor);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final invoiceIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameNormalizedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final quantityParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final unitPriceMinorParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final lineTotalMinorParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = InvoiceItemEntity(
          id: idParam,
          invoiceId: invoiceIdParam,
          name: nameParam,
          nameNormalized: nameNormalizedParam,
          quantity: quantityParam,
          unitPriceMinor: unitPriceMinorParam,
          lineTotalMinor: lineTotalMinorParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DatabaseMetadataEntity] entity fields to define ObjectBox queries.
class DatabaseMetadataEntity_ {
  /// See [DatabaseMetadataEntity.id].
  static final id = obx.QueryIntegerProperty<DatabaseMetadataEntity>(
    _entities[0].properties[0],
  );

  /// See [DatabaseMetadataEntity.key].
  static final key = obx.QueryStringProperty<DatabaseMetadataEntity>(
    _entities[0].properties[1],
  );

  /// See [DatabaseMetadataEntity.value].
  static final value = obx.QueryStringProperty<DatabaseMetadataEntity>(
    _entities[0].properties[2],
  );

  /// See [DatabaseMetadataEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<DatabaseMetadataEntity>(
    _entities[0].properties[3],
  );
}

/// [InvoiceEntity] entity fields to define ObjectBox queries.
class InvoiceEntity_ {
  /// See [InvoiceEntity.id].
  static final id = obx.QueryIntegerProperty<InvoiceEntity>(
    _entities[1].properties[0],
  );

  /// See [InvoiceEntity.merchant].
  static final merchant = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[1],
  );

  /// See [InvoiceEntity.merchantNormalized].
  static final merchantNormalized = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[2],
  );

  /// See [InvoiceEntity.documentType].
  static final documentType = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[3],
  );

  /// See [InvoiceEntity.purchaseDate].
  static final purchaseDate = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[4],
  );

  /// See [InvoiceEntity.totalMinor].
  static final totalMinor = obx.QueryIntegerProperty<InvoiceEntity>(
    _entities[1].properties[5],
  );

  /// See [InvoiceEntity.currencyCode].
  static final currencyCode = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[6],
  );

  /// See [InvoiceEntity.warrantyMonths].
  static final warrantyMonths = obx.QueryIntegerProperty<InvoiceEntity>(
    _entities[1].properties[7],
  );

  /// See [InvoiceEntity.warrantyEndDate].
  static final warrantyEndDate = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[8],
  );

  /// See [InvoiceEntity.invoiceNumber].
  static final invoiceNumber = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[9],
  );

  /// See [InvoiceEntity.rawExtractedText].
  static final rawExtractedText = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[10],
  );

  /// See [InvoiceEntity.searchableText].
  static final searchableText = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[11],
  );

  /// See [InvoiceEntity.keywordText].
  static final keywordText = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[12],
  );

  /// See [InvoiceEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[13],
  );

  /// See [InvoiceEntity.thumbnailPath].
  static final thumbnailPath = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[14],
  );

  /// See [InvoiceEntity.sourceType].
  static final sourceType = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[15],
  );

  /// See [InvoiceEntity.embedding].
  static final embedding = obx.QueryHnswProperty<InvoiceEntity>(
    _entities[1].properties[16],
  );

  /// See [InvoiceEntity.embeddingModelId].
  static final embeddingModelId = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[17],
  );

  /// See [InvoiceEntity.embeddingDimensions].
  static final embeddingDimensions = obx.QueryIntegerProperty<InvoiceEntity>(
    _entities[1].properties[18],
  );

  /// See [InvoiceEntity.searchTextSchemaVersion].
  static final searchTextSchemaVersion =
      obx.QueryIntegerProperty<InvoiceEntity>(_entities[1].properties[19]);

  /// See [InvoiceEntity.extractionModelId].
  static final extractionModelId = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[20],
  );

  /// See [InvoiceEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[21],
  );

  /// See [InvoiceEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[22],
  );

  /// See [InvoiceEntity.reviewedAt].
  static final reviewedAt = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[23],
  );

  /// See [InvoiceEntity.embeddingStatus].
  static final embeddingStatus = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[24],
  );

  /// See [InvoiceEntity.embeddingSchemaVersion].
  static final embeddingSchemaVersion = obx.QueryIntegerProperty<InvoiceEntity>(
    _entities[1].properties[25],
  );

  /// See [InvoiceEntity.embeddingUpdatedAt].
  static final embeddingUpdatedAt = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[26],
  );

  /// See [InvoiceEntity.embeddingFailureCode].
  static final embeddingFailureCode = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[27],
  );

  /// See [InvoiceEntity.documentTypeNormalized].
  static final documentTypeNormalized = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[28],
  );

  /// See [InvoiceEntity.embeddingAttemptId].
  static final embeddingAttemptId = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[29],
  );
}

/// [InvoiceItemEntity] entity fields to define ObjectBox queries.
class InvoiceItemEntity_ {
  /// See [InvoiceItemEntity.id].
  static final id = obx.QueryIntegerProperty<InvoiceItemEntity>(
    _entities[2].properties[0],
  );

  /// See [InvoiceItemEntity.invoiceId].
  static final invoiceId = obx.QueryIntegerProperty<InvoiceItemEntity>(
    _entities[2].properties[1],
  );

  /// See [InvoiceItemEntity.name].
  static final name = obx.QueryStringProperty<InvoiceItemEntity>(
    _entities[2].properties[2],
  );

  /// See [InvoiceItemEntity.nameNormalized].
  static final nameNormalized = obx.QueryStringProperty<InvoiceItemEntity>(
    _entities[2].properties[3],
  );

  /// See [InvoiceItemEntity.quantity].
  static final quantity = obx.QueryDoubleProperty<InvoiceItemEntity>(
    _entities[2].properties[4],
  );

  /// See [InvoiceItemEntity.unitPriceMinor].
  static final unitPriceMinor = obx.QueryIntegerProperty<InvoiceItemEntity>(
    _entities[2].properties[5],
  );

  /// See [InvoiceItemEntity.lineTotalMinor].
  static final lineTotalMinor = obx.QueryIntegerProperty<InvoiceItemEntity>(
    _entities[2].properties[6],
  );
}
